name: 'Find changes'
description: "Find changes upon 'pull_request' or default branch 'push' events"
author: 'anttiharju'

branding:
  icon: 'git-pull-request'
  color: 'purple'

# TBD
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# TBD
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
